#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// Map Group 0
#define MAP_PLAYGROUND         (0 | (0 << 8))
#define MAP_PETRIFACTHEIM_CITY (1 | (0 << 8))
#define MAP_EVER_GRANDE_CITY   (2 | (0 << 8))
#define MAP_OLDALE_TOWN        (3 | (0 << 8))
#define MAP_DEWFORD_TOWN       (4 | (0 << 8))
#define MAP_LAVARIDGE_TOWN     (5 | (0 << 8))
#define MAP_FALLARBOR_TOWN     (6 | (0 << 8))
#define MAP_VERDANTURF_TOWN    (7 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN    (8 | (0 << 8))

// Map Group 1

// Map Group 2
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (2 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (2 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (2 << 8))

// Map Group 3
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (3 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (3 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (3 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (3 << 8))

// Map Group 4
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (4 << 8))

// Map Group 5
#define MAP_FALLARBOR_TOWN_MART                    (0 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (5 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (5 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (5 << 8))

// Map Group 6
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (6 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (6 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (6 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (6 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (6 << 8))

// Map Group 7
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (7 << 8))

// Map Group 8

// Map Group 9

// Map Group 10

// Map Group 11

// Map Group 12

// Map Group 13

// Map Group 14

// Map Group 15

// Map Group 16
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (16 << 8))

// Map Group 17
#define MAP_METEOR_FALLS_1F_1R                       (0 | (17 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (17 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (17 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (17 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (17 << 8))
#define MAP_DESERT_RUINS                             (5 | (17 << 8))
#define MAP_GRANITE_CAVE_1F                          (6 | (17 << 8))
#define MAP_GRANITE_CAVE_B1F                         (7 | (17 << 8))
#define MAP_GRANITE_CAVE_B2F                         (8 | (17 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (9 | (17 << 8))
#define MAP_PETALBURG_WOODS                          (10 | (17 << 8))
#define MAP_MT_CHIMNEY                               (11 | (17 << 8))
#define MAP_JAGGED_PASS                              (12 | (17 << 8))
#define MAP_FIERY_PATH                               (13 | (17 << 8))
#define MAP_MT_PYRE_1F                               (14 | (17 << 8))
#define MAP_MT_PYRE_2F                               (15 | (17 << 8))
#define MAP_MT_PYRE_3F                               (16 | (17 << 8))
#define MAP_MT_PYRE_4F                               (17 | (17 << 8))
#define MAP_MT_PYRE_5F                               (18 | (17 << 8))
#define MAP_MT_PYRE_6F                               (19 | (17 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (20 | (17 << 8))
#define MAP_MT_PYRE_SUMMIT                           (21 | (17 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (22 | (17 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (23 | (17 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (24 | (17 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (25 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (26 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (27 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (28 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (29 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (30 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (31 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (32 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (33 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (34 | (17 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (35 | (17 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (36 | (17 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (37 | (17 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (38 | (17 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (39 | (17 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (40 | (17 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (41 | (17 << 8))
#define MAP_VICTORY_ROAD_1F                          (42 | (17 << 8))
#define MAP_VICTORY_ROAD_B1F                         (43 | (17 << 8))
#define MAP_VICTORY_ROAD_B2F                         (44 | (17 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (45 | (17 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (46 | (17 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (47 | (17 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (48 | (17 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (49 | (17 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (50 | (17 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (51 | (17 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (52 | (17 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (53 | (17 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (54 | (17 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (55 | (17 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (56 | (17 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (57 | (17 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (58 | (17 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (59 | (17 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (60 | (17 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (61 | (17 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (62 | (17 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (63 | (17 << 8))
#define MAP_ISLAND_CAVE                              (64 | (17 << 8))
#define MAP_ANCIENT_TOMB                             (65 | (17 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (66 | (17 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (67 | (17 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (68 | (17 << 8))
#define MAP_SCORCHED_SLAB                            (69 | (17 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (70 | (17 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (71 | (17 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (72 | (17 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (73 | (17 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (74 | (17 << 8))
#define MAP_SKY_PILLAR_1F                            (75 | (17 << 8))
#define MAP_SKY_PILLAR_2F                            (76 | (17 << 8))
#define MAP_SKY_PILLAR_3F                            (77 | (17 << 8))
#define MAP_SKY_PILLAR_4F                            (78 | (17 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (79 | (17 << 8))
#define MAP_SKY_PILLAR_5F                            (80 | (17 << 8))
#define MAP_SKY_PILLAR_TOP                           (81 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (82 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (83 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (84 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (85 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (86 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (87 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (88 | (17 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (89 | (17 << 8))
#define MAP_MIRAGE_TOWER_1F                          (90 | (17 << 8))
#define MAP_MIRAGE_TOWER_2F                          (91 | (17 << 8))
#define MAP_MIRAGE_TOWER_3F                          (92 | (17 << 8))
#define MAP_MIRAGE_TOWER_4F                          (93 | (17 << 8))
#define MAP_DESERT_UNDERPASS                         (94 | (17 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (95 | (17 << 8))
#define MAP_ARTISAN_CAVE_1F                          (96 | (17 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (97 | (17 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (98 | (17 << 8))
#define MAP_MARINE_CAVE_END                          (99 | (17 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (100 | (17 << 8))
#define MAP_TERRA_CAVE_END                           (101 | (17 << 8))
#define MAP_ALTERING_CAVE                            (102 | (17 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (103 | (17 << 8))

// Map Group 18
#define MAP_SECRET_BASE_RED_CAVE1           (0 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1         (1 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1          (2 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1        (3 | (18 << 8))
#define MAP_SECRET_BASE_TREE1               (4 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB1              (5 | (18 << 8))
#define MAP_SECRET_BASE_RED_CAVE2           (6 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2         (7 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2          (8 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2        (9 | (18 << 8))
#define MAP_SECRET_BASE_TREE2               (10 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB2              (11 | (18 << 8))
#define MAP_SECRET_BASE_RED_CAVE3           (12 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3         (13 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3          (14 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3        (15 | (18 << 8))
#define MAP_SECRET_BASE_TREE3               (16 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB3              (17 | (18 << 8))
#define MAP_SECRET_BASE_RED_CAVE4           (18 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4         (19 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4          (20 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4        (21 | (18 << 8))
#define MAP_SECRET_BASE_TREE4               (22 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB4              (23 | (18 << 8))
#define MAP_BATTLE_COLOSSEUM_2P             (24 | (18 << 8))
#define MAP_TRADE_CENTER                    (25 | (18 << 8))
#define MAP_RECORD_CORNER                   (26 | (18 << 8))
#define MAP_BATTLE_COLOSSEUM_4P             (27 | (18 << 8))
#define MAP_CONTEST_HALL                    (28 | (18 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_29 (29 | (18 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_30 (30 | (18 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_31 (31 | (18 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_32 (32 | (18 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_33 (33 | (18 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_34 (34 | (18 << 8))
#define MAP_CONTEST_HALL_BEAUTY             (35 | (18 << 8))
#define MAP_CONTEST_HALL_TOUGH              (36 | (18 << 8))
#define MAP_CONTEST_HALL_COOL               (37 | (18 << 8))
#define MAP_CONTEST_HALL_SMART              (38 | (18 << 8))
#define MAP_CONTEST_HALL_CUTE               (39 | (18 << 8))
#define MAP_SS_TIDAL_CORRIDOR               (40 | (18 << 8))
#define MAP_SS_TIDAL_LOWER_DECK             (41 | (18 << 8))
#define MAP_SS_TIDAL_ROOMS                  (42 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01         (43 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02         (44 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03         (45 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04         (46 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05         (47 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06         (48 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07         (49 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08         (50 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09         (51 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10         (52 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11         (53 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12         (54 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13         (55 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14         (56 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15         (57 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16         (58 | (18 << 8))
#define MAP_UNION_ROOM                      (59 | (18 << 8))

// Map Group 19
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (19 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (19 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (19 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (19 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (19 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (19 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (19 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (19 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (19 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (19 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (19 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (19 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (19 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (19 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (19 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (19 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (19 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (19 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (19 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (19 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (19 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (19 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (19 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (19 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (19 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (19 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (19 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (19 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (19 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (19 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (19 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (19 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (19 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (19 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (19 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (19 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (19 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (19 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (19 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (19 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (19 << 8))

#define MAP_GROUPS_COUNT 20

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
