#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// overworldGroup
#define MAP_PLAYGROUND         (0 | (0 << 8))
#define MAP_PETRIFACTHEIM_CITY (1 | (0 << 8))
#define MAP_ROUTE01            (2 | (0 << 8))

// petrifactheimGroup
#define MAP_UNDERWATER_GYM (0 | (1 << 8))

// poiGroup
#define MAP_DESERT_RUINS              (0 | (2 << 8))
#define MAP_ISLAND_CAVE               (1 | (2 << 8))
#define MAP_ANCIENT_TOMB              (2 | (2 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM (3 | (2 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM (4 | (2 << 8))
#define MAP_ALTERING_CAVE             (5 | (2 << 8))

// miscGroup
#define MAP_SECRET_BASE_RED_CAVE1                           (0 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1                         (1 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1                          (2 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1                        (3 | (3 << 8))
#define MAP_SECRET_BASE_TREE1                               (4 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB1                              (5 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE2                           (6 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2                         (7 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2                          (8 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2                        (9 | (3 << 8))
#define MAP_SECRET_BASE_TREE2                               (10 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB2                              (11 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE3                           (12 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3                         (13 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3                          (14 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3                        (15 | (3 << 8))
#define MAP_SECRET_BASE_TREE3                               (16 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB3                              (17 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE4                           (18 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4                         (19 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4                          (20 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4                        (21 | (3 << 8))
#define MAP_SECRET_BASE_TREE4                               (22 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB4                              (23 | (3 << 8))
#define MAP_BATTLE_COLOSSEUM_2P                             (24 | (3 << 8))
#define MAP_TRADE_CENTER                                    (25 | (3 << 8))
#define MAP_RECORD_CORNER                                   (26 | (3 << 8))
#define MAP_BATTLE_COLOSSEUM_4P                             (27 | (3 << 8))
#define MAP_CONTEST_HALL                                    (28 | (3 << 8))
#define MAP_CONTEST_HALL_BEAUTY                             (29 | (3 << 8))
#define MAP_CONTEST_HALL_TOUGH                              (30 | (3 << 8))
#define MAP_CONTEST_HALL_COOL                               (31 | (3 << 8))
#define MAP_CONTEST_HALL_SMART                              (32 | (3 << 8))
#define MAP_CONTEST_HALL_CUTE                               (33 | (3 << 8))
#define MAP_SS_TIDAL_CORRIDOR                               (34 | (3 << 8))
#define MAP_SS_TIDAL_LOWER_DECK                             (35 | (3 << 8))
#define MAP_SS_TIDAL_ROOMS                                  (36 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01                         (37 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02                         (38 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03                         (39 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04                         (40 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05                         (41 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06                         (42 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07                         (43 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08                         (44 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09                         (45 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10                         (46 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11                         (47 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12                         (48 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13                         (49 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14                         (50 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15                         (51 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16                         (52 | (3 << 8))
#define MAP_UNION_ROOM                                      (53 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTHWEST                           (54 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (55 | (3 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (56 | (3 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (57 | (3 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (58 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (59 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (60 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (61 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (62 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (63 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (64 | (3 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (65 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (66 | (3 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (67 | (3 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (68 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (69 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (70 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (71 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (72 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (73 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (74 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (75 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (76 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (77 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (78 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (79 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (80 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (81 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (82 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (83 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (84 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (85 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (86 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (87 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (88 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (89 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (90 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (91 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (92 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (93 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (94 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (95 | (3 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (96 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (97 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (98 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (99 | (3 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (100 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (101 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (102 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (103 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (104 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (105 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (106 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (107 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (108 | (3 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (109 | (3 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (110 | (3 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (111 | (3 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (112 | (3 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (113 | (3 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (114 | (3 << 8))
#define MAP_TRAINER_HILL_1F                                 (115 | (3 << 8))
#define MAP_TRAINER_HILL_2F                                 (116 | (3 << 8))
#define MAP_TRAINER_HILL_3F                                 (117 | (3 << 8))
#define MAP_TRAINER_HILL_4F                                 (118 | (3 << 8))
#define MAP_TRAINER_HILL_ROOF                               (119 | (3 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (120 | (3 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (121 | (3 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (122 | (3 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (123 | (3 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (124 | (3 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (125 | (3 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (126 | (3 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (127 | (3 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (128 | (3 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (129 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (130 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (131 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (132 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (133 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (134 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (135 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (136 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (137 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (138 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (139 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (140 | (3 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (141 | (3 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (142 | (3 << 8))

#define MAP_GROUPS_COUNT 4

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
