#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// Map Group 0
#define MAP_PLAYGROUND         (0 | (0 << 8))
#define MAP_PETRIFACTHEIM_CITY (1 | (0 << 8))
#define MAP_ROUTE01            (2 | (0 << 8))

// Map Group 1
#define MAP_UNDERWATER_GYM (0 | (1 << 8))

// Map Group 2
#define MAP_DESERT_RUINS              (0 | (2 << 8))
#define MAP_ISLAND_CAVE               (1 | (2 << 8))
#define MAP_ANCIENT_TOMB              (2 | (2 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM (3 | (2 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM (4 | (2 << 8))
#define MAP_ALTERING_CAVE             (5 | (2 << 8))

// Map Group 3
#define MAP_SECRET_BASE_RED_CAVE1                           (0 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1                         (1 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1                          (2 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1                        (3 | (3 << 8))
#define MAP_SECRET_BASE_TREE1                               (4 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB1                              (5 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE2                           (6 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2                         (7 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2                          (8 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2                        (9 | (3 << 8))
#define MAP_SECRET_BASE_TREE2                               (10 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB2                              (11 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE3                           (12 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3                         (13 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3                          (14 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3                        (15 | (3 << 8))
#define MAP_SECRET_BASE_TREE3                               (16 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB3                              (17 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE4                           (18 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4                         (19 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4                          (20 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4                        (21 | (3 << 8))
#define MAP_SECRET_BASE_TREE4                               (22 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB4                              (23 | (3 << 8))
#define MAP_BATTLE_COLOSSEUM_2P                             (24 | (3 << 8))
#define MAP_TRADE_CENTER                                    (25 | (3 << 8))
#define MAP_RECORD_CORNER                                   (26 | (3 << 8))
#define MAP_BATTLE_COLOSSEUM_4P                             (27 | (3 << 8))
#define MAP_CONTEST_HALL                                    (28 | (3 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_29                 (29 | (3 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_30                 (30 | (3 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_31                 (31 | (3 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_32                 (32 | (3 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_33                 (33 | (3 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_34                 (34 | (3 << 8))
#define MAP_CONTEST_HALL_BEAUTY                             (35 | (3 << 8))
#define MAP_CONTEST_HALL_TOUGH                              (36 | (3 << 8))
#define MAP_CONTEST_HALL_COOL                               (37 | (3 << 8))
#define MAP_CONTEST_HALL_SMART                              (38 | (3 << 8))
#define MAP_CONTEST_HALL_CUTE                               (39 | (3 << 8))
#define MAP_SS_TIDAL_CORRIDOR                               (40 | (3 << 8))
#define MAP_SS_TIDAL_LOWER_DECK                             (41 | (3 << 8))
#define MAP_SS_TIDAL_ROOMS                                  (42 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01                         (43 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02                         (44 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03                         (45 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04                         (46 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05                         (47 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06                         (48 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07                         (49 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08                         (50 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09                         (51 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10                         (52 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11                         (53 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12                         (54 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13                         (55 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14                         (56 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15                         (57 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16                         (58 | (3 << 8))
#define MAP_UNION_ROOM                                      (59 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTHWEST                           (60 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (61 | (3 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (62 | (3 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (63 | (3 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (64 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (65 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (66 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (67 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (68 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (69 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (70 | (3 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (71 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (72 | (3 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (73 | (3 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (74 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (75 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (76 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (77 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (78 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (79 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (80 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (81 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (82 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (83 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (84 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (85 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (86 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (87 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (88 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (89 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (90 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (91 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (92 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (93 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (94 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (95 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (96 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (97 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (98 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (99 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (100 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (101 | (3 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (102 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (103 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (104 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (105 | (3 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (106 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (107 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (108 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (109 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (110 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (111 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (112 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (113 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (114 | (3 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (115 | (3 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (116 | (3 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (117 | (3 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (118 | (3 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (119 | (3 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (120 | (3 << 8))
#define MAP_TRAINER_HILL_1F                                 (121 | (3 << 8))
#define MAP_TRAINER_HILL_2F                                 (122 | (3 << 8))
#define MAP_TRAINER_HILL_3F                                 (123 | (3 << 8))
#define MAP_TRAINER_HILL_4F                                 (124 | (3 << 8))
#define MAP_TRAINER_HILL_ROOF                               (125 | (3 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (126 | (3 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (127 | (3 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (128 | (3 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (129 | (3 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (130 | (3 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (131 | (3 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (132 | (3 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (133 | (3 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (134 | (3 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (135 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (136 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (137 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (138 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (139 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (140 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (141 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (142 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (143 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (144 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (145 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (146 | (3 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (147 | (3 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (148 | (3 << 8))

#define MAP_GROUPS_COUNT 4

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
